# Generated by Django 5.1.2 on 2024-11-07 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Module_title', models.CharField(max_length=255)),
                ('phase', models.CharField(choices=[('Phase 1', 'PHASE 1'), ('Phase 2', 'PHASE 2'), ('Phase 3', 'PHASE 3'), ('Phase 4', 'PHASE 4'), ('Phase 5', 'PHASE 5'), ('Phase 6', 'PHASE 6')], max_length=20)),
                ('difficulty', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=20)),
            ],
        ),
    ]
