# Generated by Django 5.1.2 on 2024-11-16 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_module_title_module_module'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='Module',
            new_name='title',
        ),
    ]
